# NumPy教程 | NumPy Tutorial

作者: 宛莹
日期: 2025年1月 

Author: Wanying
Date: January 2025

In [2]:
# 导入NumPy模块 | Import the NumPy module
import numpy as np

## 什么是NumPy? | What is NumPy?

- NumPy是Python进行科学计算的基础包。它是一个Python库,提供多维数组对象,各种派生对象(如掩码数组和矩阵),以及用于数组快速操作的各种API,有包括数学、逻辑、形状操作、排序、选择、输入输出、离散傅立叶变换、基本线性代数、基本统计运算和随机模拟等等。
- NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

## 数组对象 | Array Objects
- NumPy中的核心对象是同构多维数组(homogeneous multidimensional array)。它是一个元素表(通常是数字),所有类型都相同,由非负整数元组索引。 在NumPy中维度称为轴(axes)。
- The core object in NumPy is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.


In [74]:
# 创建一维数组 | Create a 1-D array
x = np.array([5, 2, 3])
print(x)
print(type(x))
print(x.shape)
print(x[0], x[1], x[2])
x[0] = 0
print(x)

[5 2 3]
<class 'numpy.ndarray'>
(3,)
5 2 3
[0 2 3]


In [75]:
# 创建二维数组 | Create a 2-D array 
b = np.array([[5,2,3],[3,0,4]]) 
print(b)
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

[[5 2 3]
 [3 0 4]]
(2, 3)
5 2 3


In [76]:
# 创建三维数组 | Create a 3-D array 
z = np.array([[5],[3],[2],[0]]) 
print(z)
print(z.shape)
print(z[0], z[1], z[3])

[[5]
 [3]
 [2]
 [0]]
(4, 1)
[5] [3] [0]



## 创建数组的函数 | Array Creation Functions

There are several ways to create arrays in NumPy:
- `np.array()`: 从Python列表或元组创建数组。Created an array from a regular Python list or tuple
- `np.zeros()`: 创建指定形状和类型的数组,并用0填充。Create an array filled with zeros 
- `np.ones()`: 创建指定形状和类型的数组,并用1填充。Create an array filled with ones
- `np.empty()`: 创建指定形状和类型的数组,不初始化元素。Create an array, but leave its content uninitialized
- `np.arange()`: 创建数字序列。Create an array with evenly spaced values
- `np.linspace()`: 创建指定数量的数组,并在指定的开始值和结束值之间平均分布。Create an array with evenly spaced values over a specified interval

In [77]:
# 创建数组的函数 | Array Creation Functions
print(np.zeros((3, 4)))
print(np.ones((2, 3, 4), dtype=np.int16))
print(np.empty((2, 3))) #  创建的数组元素的值是未初始化的随机值,取决于内存的状态。这个函数通常用在数组的大小已知,但是元素的值无关紧要的情况下,可以节省初始化时间。
print(np.arange(10, 30, 5)) # 这里从 10 开始,到 30 结束(不包括30),步长为 5。
print(np.linspace(0, 2, 9)) # 函数有三个参数:起始值,终止值(包含)和生成的样本数。

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]
[10 15 20 25]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


## 基本操作 | Basic Operations

数组上的算术运算符会应用到 元素级别 | Arithmetic operators on arrays apply elementwise.

In [78]:
a = np.array([20,30,40,50])
b = np.arange(4) # 当只提供一个参数时,np.arange() 将其解释为序列的终止值(不包括在内),并默认从 0 开始,步长为 1
print(b)
c = a - b
print(c)
print(b**2)
print(10*np.sin(a))
print(a < 35)

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


NumPy中的乘积运算符`*`在数组中逐元素运算。 矩阵乘积可以使用`@`运算符或`dot()`函数执行:
The product operator `*` operates elementwise in NumPy arrays. The matrix product can be performed using the `@` operator or the `dot()` function:  

In [79]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
print(A)
print(B)
print(A * B)
print(A @ B)
print(A.dot(B))

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


有些操作(例如 `+=` 和 `*=`)会更直接更改被操作的矩阵数组而不会创建新矩阵数组.
Some operations, such as `+=` and `*=`, act in place to modify an existing array rather than create a new one.

In [80]:
a = np.ones((2,3), dtype=int)
print(a)
b = np.random.random((2,3))
print(b)
a *= 3
print(a)
b += a
print(b)

[[1 1 1]
 [1 1 1]]
[[0.89402767 0.121229   0.66474042]
 [0.20429678 0.60461972 0.20410285]]
[[3 3 3]
 [3 3 3]]
[[3.89402767 3.121229   3.66474042]
 [3.20429678 3.60461972 3.20410285]]


许多一元操作, 例如计算数组中所有元素的总和, 都是作为`ndarray`类的方法实现的。
Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the `ndarray` class.

In [81]:
a = np.random.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[0.36999814 0.07868103 0.18486051]
 [0.1669022  0.62037209 0.33709059]]
1.757904556566467
0.07868102564452628
0.6203720930930913


默认情况下,这些操作适用于数组,就像它是一个数字列表一样,无论其形状如何。 但是,通过指定`axis`参数,可以沿数组的指定轴应用操作:

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the `axis` parameter we can apply an operation along the specified axis of an array:

In [82]:
b = np.arange(12).reshape(3,4)
print(b)
print(b.sum(axis=0))  # sum of each column
print(b.min(axis=1))  # min of each row 
print(b.cumsum(axis=1))  # cumulative sum along each row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


## 通函数 | Universal Functions

NumPy提供熟悉的数学函数,例如sin,cos和exp。 在NumPy中,这些被称为"通函数"(ufunc)。 在NumPy中,这些函数在数组上按元素进行运算,产生一个数组作为输出。
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called "universal functions"(ufunc). In NumPy, these functions operate elementwise on an array, producing an array as output.

In [83]:
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))
C = np.array([2., -1., 4.])
print(np.add(B, C))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]


另见:
- [NumPy Ufunc的完整列表 | The complete list of NumPy Ufuncs](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs)

## 索引、切片和迭代 | Indexing, Slicing and Iterating

**一维**数组可以进行索引、切片和迭代操作的,就像 Python 列表一样:
**One-dimensional** arrays can be indexed, sliced and iterated over, much like Python lists:


In [84]:
a = np.arange(10)**3
print(a)
print(a[2])
print(a[2:5])
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000
print(a)
print(a[ : :-1])
for i in a:
    print(i**(1/3.))

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[-1000     1 -1000    27 -1000   125   216   343   512   729]
[  729   512   343   216   125 -1000    27 -1000     1 -1000]
nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


C:\Users\gufan\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in power
  if __name__ == "__main__":


**多维**数组每个轴可以有一个索引。这些索引以逗号分隔的元组给出
**Multidimensional** arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [85]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
print(b)
print(b[2,3])
print(b[0:5, 1])
print(b[ : ,1])
print(b[1:3, : ])
print(b[-1])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]
[40 41 42 43]


当提供的索引少于轴的数量时,缺失的索引被认为是一个完整的切片
When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [86]:
print(b[-1])  # the same as b[-1,:]

[40 41 42 43]


`b[i]` 方括号中的表达式 `i` 被视为后面紧跟着 `:` 的多个实例,用于表示剩余轴。 NumPy还允许你使用三个点写为 `b[i,...]`。
The expression within the brackets `b[i]` in is treated as if it was `i` followed by as many instances of `:` as needed to represent the remaining axes. NumPy also allows you to write this using dots as `b[i,...]`.

三个点(`...`)表示产生完整索引元组所需的冒号。例如, 如果 `x` 是rank为5的数组(即,它具有5个轴),那么:
- `x[1,2,...]` 相当于 `x[1,2,:,:,:]`, 
- `x[...,3]` 等效于 `x[:,:,:,:,3]`
- `x[4,...,5,:]` 等效于 `x[4,:,:,5,:]`

The dots (`...`) represent as many colons as needed to produce a complete indexing tuple. For example, if `x` is an array with 5 axes, then:
- `x[1,2,...]` is equivalent to `x[1,2,:,:,:]`,
- `x[...,3]` to `x[:,:,:,:,3]` 
- `x[4,...,5,:]` to `x[4,:,:,5,:]`.

In [87]:
c = np.array([[[  0,  1,  2],  
               [ 10, 12, 13]],
              [[100,101,102],
               [110,112,113]]])
print(c.shape)
print(c[1,...]) 
print(c[...,2])

(2, 2, 3)
[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]


对多维数组进行 **迭代(Iterating)** 是相对于第一个轴完成的:
**Iterating** over multidimensional arrays is done with respect to the first axis:

In [88]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


但是, 如果想要对数组中的每个元素执行操作, 可以使用 `flat` 属性,该属性是数组的所有元素的迭代器:
However, if one wants to perform an operation on each element in the array, one can use the `flat` attribute which is an iterator over all the elements of the array:

In [89]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


另见:
- [NumPy索引的基础 | Indexing basics](https://numpy.org/doc/stable/user/basics.indexing.html)

## 形状操纵 | Shape Manipulation

### 改变数组的形状 | Changing the shape of an array

一个数组的形状由它每个轴上的元素数量决定 | An array has a shape given by the number of elements along each axis:

In [90]:
a = np.floor(10*np.random.random((3,4)))
print(a)
print(a.shape)

[[8. 4. 1. 5.]
 [6. 4. 5. 8.]
 [7. 8. 9. 1.]]
(3, 4)


可以使用各种命令更改数组的形状。注意以下三个函数都返回一个修改后的数组,但不会更改原始数组:
The shape of an array can be changed with various commands. Note that the following three functions return a modified array, but do not change the original array:

In [91]:
print(a.ravel())  # flattens the array
print(a.reshape(6,2)) # returns the array with a modified shape
print(a.T) # returns the array, transposed
x = a.T
x[1,1] = 1000 #注意a的值被修改了
print(a) 
print(a.T.shape)
print(a.shape)

[8. 4. 1. 5. 6. 4. 5. 8. 7. 8. 9. 1.]
[[8. 4.]
 [1. 5.]
 [6. 4.]
 [5. 8.]
 [7. 8.]
 [9. 1.]]
[[8. 6. 7.]
 [4. 4. 8.]
 [1. 5. 9.]
 [5. 8. 1.]]
[[   8.    4.    1.    5.]
 [   6. 1000.    5.    8.]
 [   7.    8.    9.    1.]]
(4, 3)
(3, 4)


由 `ravel()` 展平的数组元素的顺序通常是"C风格",也就是说,最右边的索引"变化最快",因此[0,0]之后的元素是[0,1]。 如果将数组重新整形(reshape)为其他形状,则该数组将被视为"C风格"。 NumPy通常会创建按此顺序存储的数组,因此`ravel()`通常不需要复制其参数,但如果数组是通过获取另一个数组的切片或使用不常见的选项创建的,则可能需要复制它。 `ravel()`函数的应用和作用与`reshape(-1)`类似。

The order of the elements in the array resulting from `ravel()` is normally "C-style", that is, the rightmost index "changes the fastest", so the element after [0,0] is [0,1]. If the array is reshaped to some other shape, the array is treated as "C-style". NumPy normally creates arrays stored in this order, so `ravel()` will usually not need to copy its argument, but if the array was made by taking slices of another array or created with unusual options, it may need to be copied. The functions `ravel()` and `reshape()` can also be instructed, using an optional argument, to use FORTRAN-style arrays, in which the leftmost index changes the fastest.

In [92]:
print(a.reshape(2, 6))

[[   8.    4.    1.    5.    6. 1000.]
 [   5.    8.    7.    8.    9.    1.]]


另见:
- [reshape的各种例子 | Various examples of reshape](https://numpy.org/doc/stable/user/quickstart.html#quickstart-shape-manipulation)

### 数组的堆叠 | Stacking together different arrays

几个数组可以沿不同的轴堆叠在一起 
Several arrays can be stacked together along different axes:

In [93]:
a = np.floor(10*np.random.random((2,2)))
print(a)
b = np.floor(10*np.random.random((2,2)))
print(b) 
print(np.vstack((a,b)))
print(np.hstack((a,b)))


[[7. 1.]
 [5. 3.]]
[[1. 0.]
 [8. 9.]]
[[7. 1.]
 [5. 3.]
 [1. 0.]
 [8. 9.]]
[[7. 1. 1. 0.]
 [5. 3. 8. 9.]]


该函数将一维数组作为列堆叠到二维数组中。它的效果相当于vstack只是输入数组被作为一维数组引用。
The function `column_stack` stacks 1D arrays as columns into a 2D array. It is equivalent to `hstack` only for 2D arrays.

In [94]:
print(np.column_stack((a,b))) # with 2D arrays

[[7. 1. 1. 0.]
 [5. 3. 8. 9.]]


对于具有两个以上维度的数组,`hstack`沿其第二轴堆叠,`vstack`沿其第一轴堆叠,`concatenate`允许可选参数给出连接应发生的轴。

For arrays of with more than two dimensions, `hstack` stacks along their second axes, `vstack` stacks along their first axes, and `concatenate` allows for an optional arguments giving the number of the axis along which the concatenation should happen.

In [95]:
a = np.floor(10*np.random.random((2,2)))
print(a.T)
print(np.hstack((a,a.T)))
print(np.vstack((a,a.T)))
print(np.concatenate((a, a.T), axis=1))
print(np.concatenate((a, a.T), axis=0))

[[5. 7.]
 [5. 0.]]
[[5. 5. 5. 7.]
 [7. 0. 5. 0.]]
[[5. 5.]
 [7. 0.]
 [5. 7.]
 [5. 0.]]
[[5. 5. 5. 7.]
 [7. 0. 5. 0.]]
[[5. 5.]
 [7. 0.]
 [5. 7.]
 [5. 0.]]



### 将一个数组拆分成几个较小的数组 | Splitting one array into several smaller ones

使用`hsplit`你可以沿着水平轴分割数组,或者使用`vsplit`沿着垂直轴分割,或者使用`array_split`允许指定沿哪个轴分割。
Using `hsplit` you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur:

In [96]:
a = np.floor(10*np.random.random((2,12)))
print(a) 
# Split a into 3
print(np.hsplit(a,3))
# Split a after the third and the fourth column
print(np.hsplit(a,(3,4)))

[[6. 3. 3. 4. 8. 3. 5. 9. 1. 1. 0. 2.]
 [9. 3. 2. 0. 2. 7. 4. 3. 2. 5. 3. 9.]]
[array([[6., 3., 3., 4.],
       [9., 3., 2., 0.]]), array([[8., 3., 5., 9.],
       [2., 7., 4., 3.]]), array([[1., 1., 0., 2.],
       [2., 5., 3., 9.]])]
[array([[6., 3., 3.],
       [9., 3., 2.]]), array([[4.],
       [0.]]), array([[8., 3., 5., 9., 1., 1., 0., 2.],
       [2., 7., 4., 3., 2., 5., 3., 9.]])]


## 拷贝和视图(Copy and View)

当计算和操作数组时,有时会将数据复制到新数组中,有时则不会。这通常是初学者混淆的根源。有三种情况:

When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases: 

### 不复制 | No Copy at All

简单分配不会复制数组对象或其数据。
Simple assignments make no copy of objects or their data.

In [97]:
a = np.arange(12)
b = a  # no new object is created
print(b is a)  # a and b are two names for the same ndarray object
b.shape = 3,4  # changes the shape of a
print(a.shape)

True
(3, 4)


Python将可变对象作为引用传递,因此函数调用不会复制。
Python passes mutable objects as references, so function calls make no copy.

In [98]:
def f(x):
    print(id(x))

print(id(a))  # id is a unique identifier of an object
f(a)

1659302405488
1659302405488


### 视图或浅拷贝 | View or Shallow Copy 

不同的数组对象可以共享相同的数据。 `view`方法创建一个查看相同数据的新数组对象。
Different array objects can share the same data. The `view` method creates a new array object that looks at the same data.

In [99]:
c = a.view()
print(c is a)
print(c.base is a)  # c is a view of the data owned by a
print(c.flags.owndata)
c.shape = 2,6  # a's shape doesn't change
print(a.shape)
c[0,4] = 1234  # a's data changes
print(a)

False
True
False
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


切片数组会返回一个视图
Slicing an array returns a view of it:


In [100]:
s = a[ : , 1:3]  # spaces added for clarity; could also be written "s = a[:,1:3]"
print(s)
s[:] = 10  # s[:] is a view of s. Note the difference between s=10 and s[:]=10
print(s)
print(a)

[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[10 10]
 [10 10]
 [10 10]]
[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]



### 深拷贝 | Deep Copy

`copy`方法生成数组及其数据的完整副本。
The `copy` method makes a complete copy of the array and its data.


In [101]:
d = a.copy()  # a new array object with new data is created
print(d is a)
print(d.base is a)  # d doesn't share anything with a 
d[0,0] = 9999
print(a)

False
False
[[   0   10   10    3]
 [1234   10   10    7]
 [   8   10   10   11]]



有时,如果不再需要原始数组,则应在切片后调用 `copy`。例如,假设a是一个巨大的中间结果,最终结果b只包含a的一小部分,则在用切片构建b时应该做一个深拷贝:

Sometimes `copy` should be called after slicing if the original array is not required anymore. For example, suppose a is a huge intermediate result and the final result b only contains a small fraction of a, a deep copy should be made when constructing b with slicing:

In [102]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a  # the memory of ``a`` can be released.

如果改为使用 `b = a[:100]`,则 `a` 由 `b` 引用,并且即使执行 `del a` 也会在内存中持久存在。
If on the other hand `b = a[:100]` is used, `a` is referenced by `b` and will persist in memory even if `del a` is executed.


## 询问 | Questions

`all` 测试数组中所有元素是否都为True.
Test whether all array elements along a given axis evaluate to True.

In [103]:
arr = np.array([[True, False], [True, True]])
print(np.all(arr)) 

False


`any`测试数组中是否存在一个或多个True. `nonzero` 返回数组中非零元素的索引.
 Test whether any array element along a given axis evaluates to True. Return the indices of the elements that are non-zero.

In [104]:
print(np.any(arr))  # 输出: True
arr = np.array([[1, 0], [0, 2]]) # nonzero: 返回数组中非零元素的索引 | Return the indices of the elements that are non-zero.
print(np.nonzero(arr))  

True
(array([0, 1], dtype=int64), array([0, 1], dtype=int64))


 `where` 根据条件返回索引.
  Return elements chosen from x or y depending on condition.

In [105]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])
condition = np.array([True, False, True, True, False])
print(np.where(condition, x, y))  # 输出: array([1, 7, 3, 4, 10])

[ 1  7  3  4 10]


## 顺序 | Ordering

In [106]:
# argmax: 返回数组中最大值的索引 | Returns the indices of the maximum values along an axis.
arr = np.array([[1, 2], [3, 4]])
print(np.argmax(arr))  # 输出: 3

# argmin: 返回数组中最小值的索引 | Returns the indices of the minimum values along an axis.
print(np.argmin(arr))  # 输出: 0

# argsort: 返回数组值从小到大的索引值 | Returns the indices that would sort an array.
arr = np.array([3, 1, 2])
print(np.argsort(arr))  # 输出: array([1, 2, 0])

# max: 返回数组中的最大值 | Return the maximum along a given axis.
print(np.max(arr))  # 输出: 3

# min: 返回数组中的最小值 | Return the minimum along a given axis.
print(np.min(arr))  # 输出: 1

# ptp: 返回数组中最大值和最小值的差 | Range of values (maximum - minimum) along a given axis.
print(np.ptp(arr))  # 输出: 2

# searchsorted: 为维持数组顺序,将值插入数组中的索引位置 | Find indices where elements should be inserted to maintain order.
arr = np.array([1, 2, 3, 4, 5])
print(np.searchsorted(arr, 3))  # 输出: 2

# sort: 对输入数组进行就地排序 | Return a sorted copy of an array.
arr = np.array([[1, 4], [3, 2]])
print(np.sort(arr))  # 输出: array([[1, 4], [2, 3]])

3
0
[1 2 0]
3
1
2
2
[[1 4]
 [2 3]]


## 运算 | Operations

`choose` 根据索引数组从数据源数组中构造一个新数组.
Construct an array from an index array and a set of arrays to choose from.

In [107]:
choices = [
    [0, 1, 2, 3],
    [10, 11, 12, 13],
    [20, 21, 22, 23],
    [30, 31, 32, 33]
]
arr = np.choose([2, 3, 1, 0], choices)
print(arr)  # 输出: array([20, 31, 12,  3])

[20 31 12  3]


`cumprod` 返回数组中元素的累积乘积. `cumsum` 返回数组中元素的累积和. `inner` 计算两个数组的内积.
 Return the cumulative product of elements along a given axis. Return the cumulative sum of the elements along a given axis.

In [121]:
arr = np.array([1, 2, 3])
print(np.cumprod(arr))  # 输出: array([1, 2, 6])
print(np.cumsum(arr))  # 输出: array([1, 3, 6])
print(np.prod(arr))  # prod: 返回数组中所有元素的乘积

[1 2 6]
[1 3 6]


`inner` 计算两个数组的内积.
Inner product of two arrays.

In [111]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([0, 1, 0])
print(np.inner(arr1, arr2))  # 输出: 2

2


`ndarray.fill` 用标量值填充数组. `put`为指定的索引位置赋值.
Fill the array with a scalar value. Replaces specified elements of an array with given values.

In [112]:
arr = np.array([1, 2, 3])
arr.fill(0) # ndarray.fill: 用标量值填充数组 | Fill the array with a scalar value.
print(arr)  # 输出: array([0, 0, 0])

[0 0 0]


In [113]:
arr = np.array([1, 2, 3, 4])
np.put(arr, [0, 2], [5, 6]) # put: 为指定的索引位置赋值 | Replaces specified elements of an array with given values.
print(arr)  # 输出: array([5, 2, 6, 4])

6
[5 2 6 4]


In [114]:
# putmask: 根据指定的掩码数组为指定的索引位置赋值 | Changes elements of an array based on conditional and input values.
arr = np.array([1, 2, 3, 4])
np.putmask(arr, arr > 2, [0, 0])
print(arr)  # 输出: array([1, 2, 0, 0])

[1 2 0 0]
6


## 基本统计 | Basic Statistics

In [115]:
# cov: 估计协方差矩阵 | Estimate a covariance matrix.
arr = np.array([[1, 2], [3, 4]])
print(np.cov(arr))  # 输出: array([[1., 1.], [1., 1.]])

# mean: 计算数组的算术平均值 | Compute the arithmetic mean along the specified axis.
arr = np.array([1, 2, 3])
print(np.mean(arr))  # 输出: 2.0

# std: 计算数组的标准差 | Compute the standard deviation along the specified axis.
print(np.std(arr))  # 输出: 0.816496580927726

# var: 计算数组的方差 | Compute the variance along the specified axis.
print(np.var(arr))  # 输出: 0.6666666666666666

[[0.5 0.5]
 [0.5 0.5]]
2.0
0.816496580927726
0.6666666666666666


## 基本线性代数 | Basic Linear Algebra

cross: 返回两个(数组)向量的叉积. dot: 计算两个数组的点积.
Return the cross product of two (arrays of) vectors. Dot product of two arrays. 

In [116]:
### cross: 返回两个(数组)向量的叉积 | Return the cross product of two (arrays of) vectors.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.cross(a, b))  # 输出: array([-3,  6, -3])

[-3  6 -3]


In [117]:
### dot: 计算两个数组的点积 | Dot product of two arrays.
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))  # 输出: array([[19, 22], [43, 50]])

[[19 22]
 [43 50]]


In [118]:
### outer: 计算两个向量的外积 | Compute the outer product of two vectors.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.outer(a, b))  # 输出: array([[ 4,  5,  6], [ 8, 10, 12], [12, 15, 18]])

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [119]:
### linalg.svd: 奇异值分解 | Singular Value Decomposition.
a = np.random.randn(3, 2)
U, s, Vt = np.linalg.svd(a)
print(U.shape, s.shape, Vt.shape)  # 输出: (3, 3) (2,) (2, 2)

(3, 3) (2,) (2, 2)


In [120]:
### vdot: 返回两个向量的点积 | Return the dot product of two vectors.
a = np.array([1+2j, 3+4j])
b = np.array([5+6j, 7+8j])
print(np.vdot(a, b))  # 输出: (70-8j)

(70-8j)


## 广播原则 | Broadcasting

广播是NumPy中一种强大的机制,它允许不同形状的数组进行算术运算。广播规则决定了如何处理不同形状的数组,使它们兼容并可以进行元素级运算。
Broadcasting is a powerful mechanism in NumPy that allows arrays with different shapes to perform arithmetic operations. The broadcasting rules determine how to handle arrays with different shapes, making them compatible and enabling element-wise operations.

广播的主要规则如下：
The main rules of broadcasting are as follows:

1. 如果两个数组的维度数不相等,那么小维度数组的形状将会在最左边补1,直到两个数组的维度数相等。
If the number of dimensions of the two arrays is not equal, the shape of the array with fewer dimensions will be padded with 1s on the left until the number of dimensions of the two arrays is equal.

2. 如果两个数组在某个维度上的长度相符或其中一个数组在该维度上长度为1,那么这两个数组就可以在该维度上进行运算。
If the length of the two arrays matches in a certain dimension, or one of the arrays has a length of 1 in that dimension, then the two arrays can be operated on in that dimension.

3. 如果两个数组在所有维度上都满足规则2,那么它们就可以进行广播。
If the two arrays satisfy rule 2 in all dimensions, then they can be broadcast.

4. 广播之后,每个数组的行为就像它的形状与输出广播的形状相同。
After broadcasting, each array behaves as if its shape is the same as the broadcast output shape.

In [3]:
# 例1: 两个一维数组相加 | Example 1: Adding two one-dimensional arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # 输出 | Output: array([5, 7, 9])

# 例2: 一维数组与一个数相加 | Example 2: Adding a one-dimensional array and a number
a = np.array([1, 2, 3])
print(a + 4)  # 输出 | Output: array([5, 6, 7])

# 例3: 二维数组与一维数组相加 | Example 3: Adding a two-dimensional array and a one-dimensional array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
print(a + b)
# 输出 | Output:
# array([[11, 22, 33],
#        [14, 25, 36]])

# 例4: 二维数组与一个数相加 | Example 4: Adding a two-dimensional array and a number
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a + 10)
# 输出 | Output:
# array([[11, 12, 13],
#        [14, 15, 16]])

[5 7 9]
[5 6 7]
[[11 22 33]
 [14 25 36]]
[[11 12 13]
 [14 15 16]]


#### 更多阅读 | More Resources

- [NumPy官方入门教程(英文) | Official NumPy tutorial](https://numpy.org/devdocs/user/quickstart.html)
- [NumPy参考手册(英文) | NumPy Reference](https://numpy.org/doc/stable/reference/index.html)
- [SciPy讲义:NumPy入门(英文) | SciPy Lecture Notes: NumPy](https://scipy-lectures.org/intro/numpy/index.html)